// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9zDT4VrbPhQp4XClPaaS3MzpKJ4yemA',
    appId: '1:1091406186943:web:674139e40a76977018390a',
    messagingSenderId: '1091406186943',
    projectId: 'test-store-app-4f7dd',
    authDomain: 'test-store-app-4f7dd.firebaseapp.com',
    storageBucket: 'test-store-app-4f7dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSy-EO_L1yFrmNb7NvgF11NUUXrPVbSk',
    appId: '1:1091406186943:android:5bd226597732140018390a',
    messagingSenderId: '1091406186943',
    projectId: 'test-store-app-4f7dd',
    storageBucket: 'test-store-app-4f7dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfd-tf94koKE7jHtUBIsM1438keDN4Y84',
    appId: '1:1091406186943:ios:30abcd5e89fa204f18390a',
    messagingSenderId: '1091406186943',
    projectId: 'test-store-app-4f7dd',
    storageBucket: 'test-store-app-4f7dd.appspot.com',
    iosClientId: '1091406186943-j3srbj3pf04hkiott57jg36n739qaoek.apps.googleusercontent.com',
    iosBundleId: 'com.example.testStoreApp',
  );
}
